name: Test

on: [push, pull_request] 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: make and run test
      shell: bash
      run: |
        mkdir -p build && cd build 
        cmake -DDOTENV_TEST=ON ..
        cmake --build .
        ctest -C Debug --verbose